version: '3.8'

services:
  # 1. The High-Speed Cache (Redis)
  redis:
    image: redis:alpine
    container_name: sentinel_redis
    ports:
      - "6379:6379"
    networks:
      - sentinel_net

  # 2. The Database (PostgreSQL)
  postgres:
    image: postgres:15-alpine
    container_name: sentinel_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: sentinel_db
    ports:
      - "5432:5432"
    networks:
      - sentinel_net

  # 3. Zookeeper (Required for Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: sentinel_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - sentinel_net

  # 4. The Message Queue (Kafka)
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: sentinel_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - sentinel_net

networks:
  sentinel_net:
    driver: bridge